version: '3.8'

# Головна назва проекту
name: iudicium

services:
  # --- BACKEND (Python/FastAPI) ---
  backend:
    # Використовуємо Dockerfile, що знаходиться у піддиректорії 'backend'
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: iudicium-backend
    ports:
      - "${APP_PORT}:8000"
    restart: always
    depends_on:
      - db
      - minio
    env_file:
      - .env

  # --- FRONTEND (React/Vite) ---
  frontend:

    build: 
      context: ./frontend
      dockerfile: dockerfile
    container_name: iudicium-frontend

    ports:
      - "${FRONTEND_PORT:-3000}:80"
    restart: always

    depends_on:
      - backend
      
    environment:
      - VITE_API_BASE_URL=http://backend:8000

  # --- DATABASE (PostgreSQL) ---
  db:
    image: postgres:17
    container_name: postgres_17
    restart: always
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  # --- OBJECT STORAGE (MinIO) ---
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "${MINIO_EXTERNAL_PORT}:9000"
      - "${MINIO_EXTERNAL_PORT_APP}:9001"
    env_file:
      - .env
    volumes:
      - minio_data:/data

volumes:
  pg_data:
  minio_data: